language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - cmake-data
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install libgtk-3-dev
  - sudo apt-get install libudev-dev

script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_CXX_COMPILER=$COMPILER ..
  - cmake --build .
