sudo: required
language: cpp


env:
  global:
   - MAKEFLAGS="-j 2"

matrix:
  include:
  
    # Linux / GCC
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'cmake', 'cmake-data']
      env:
        - COMPILERCXX='g++-5'
        - COMPILERC='gcc-5'
      
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'cmake', 'cmake-data']]
      env:
        - COMPILERCXX='g++-6'
        - COMPILERC='gcc-6'
       
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'cmake', 'cmake-data']]
      env:
        - COMPILERCXX='g++-7'
        - COMPILERC='gcc-7'
    
    # Linux / CLang
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test' 'llvm-toolchain-trusty-3.8']
          packages: ['libstdc++-5-dev', 'clang-3.8', 'cmake', 'cmake-data']
      env:
        - COMPILERCXX='clang++-3.8'
        - COMPILERC='clang-3.8'
        
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test' 'llvm-toolchain-trusty-3.9']
          packages: ['libstdc++-6-dev', 'clang-3.9', 'cmake', 'cmake-data']
      env:
        - COMPILERCXX='clang++-3.9'
        - COMPILERC='clang-3.9'
      
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['libstdc++-6-dev', 'clang-4.0', 'cmake', 'cmake-data']
      env:
        - COMPILERCXX='clang++-4.0'
        - COMPILERC='clang-4.0'
     
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['libstdc++-7-dev', 'clang-5.0',]
      env:
        - COMPILERCXX='clang++-5.0'
        - COMPILERC='clang-5.0'

before_install:
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install libgtk-3-dev
  - sudo apt-get install libudev-dev
  - export CIT_ROOT=`pwd`
  - cd $CIT_ROOT

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/3rd_party"
  - cd ${DEPS_DIR}
  #######################################################################################
  # Install a recent CMake (unless already installed on OS X)
  #######################################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake ninja || brew link --overwrite cmake
    fi
  - cmake --version


script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_C_COMPILER=$COMPILERC -DCMAKE_CXX_COMPILER=$COMPILERCXX ..
  - cmake --build .
