language: cpp
dist: trusty
sudo: required


env:
  global:
   - MAKEFLAGS="-j 2"

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - cmake-data
      env: COMPILERC=gcc-5
      env: COMPILERCXX=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - cmake
            - cmake-data
      env: COMPILERC=clang-3.8
      env: COMPILERCXX=clang++-3.8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install libgtk-3-dev
  - sudo apt-get install libudev-dev
  - sudo apt-get install libc++-dev

script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_C_COMPILER=$COMPILERC -DCMAKE_CXX_COMPILER=$COMPILERCXX ..
  - cmake --build .
